#pragma once

enum class StartRecipeResult {
  SUCCESS,
  RECIPE_NOT_FOUND,
  INGREDIENT_NOT_AVAILABLE,
  PUMP_NOT_CALIBRATED,
  INVALID_OVERRIDE,
  MACHINE_BUSY,
  NO_GLASS,
  START_FAILED
};

enum class StopRecipeResult { SUCCESS, NO_RECIPE_RUNNING };
